---
title: "02_lasso"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(gtsummary, quietly = TRUE)
library(flextable, quietly = TRUE)
library(glmnet)
## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")

```


```{r}
set.seed(555)
caregiver_all <- read_csv("new_data/data_table1_caregiver_all_paper_2023-09-20.csv")
data1 <- caregiver_all %>%
  dplyr::select(- ID, 
                -time.last, -time.first, -n.times, 
                -pss, -anxraw, -depraw, 
                -cops, -anx_score, -depr_score, -hads) %>%
  mutate(Hospital = factor(Hospital),
         Income = factor(Income),
         Education = factor(Education),
         Household = factor(Household),
         Relationship = factor(Relationship),
         Caring.Hours = factor(Caring.Hours)) %>%
  na.omit() 


X <- model.matrix(zbi ~  . * time,
                  data = data1)[,-1] %>%
  as.matrix()

y <- data1[, "zbi"] %>% as.matrix()

cv.lambda.lasso <- cv.glmnet(x = X, y = y, 
                             alpha = 1) 
plot(cv.lambda.lasso)  
```


```{r}
cv.lambda.lasso
plot(cv.lambda.lasso$glmnet.fit, 
     "lambda", label=FALSE)
```


```{r}
l.lasso.min <- cv.lambda.lasso$lambda.min
lasso.model <- glmnet(x = X, y = y,
                      alpha  = 1, 
                      lambda = l.lasso.min)
lasso.model$beta 
```



```
58 x 1 sparse Matrix of class "dgCMatrix"
                                      s0
(Intercept)                  .          
Randomize                   -2.778669780
time                         .          
Caregiver                    .          
Primary.Reason              -1.708385376
Employed                    -3.259687596
Retired                     -8.203584044
Education                    2.899906892
Language                     .          
Gender                       .          
Ethnicity                    5.072882210
Race                         0.166804848
Diagnosis                   -0.032240049
Stage                        2.484306349
Step                         6.087015826
Age                          0.033521262
Income                      -1.049116214
Household                   -0.434392562
Relationship                 .          
Caring.Hours                 0.780923411
Hospital                     0.988573423
Randomize:time              -0.031776650
time:Caregiver               .          
time:Primary.Reason          .          
time:Employed               -0.135764878
time:Retired                -0.057591503
time:Education               .          
time:Language                0.006084910
time:Gender                  0.052219835
time:Ethnicity               .          
time:Race                   -0.011112672
time:Diagnosis              -0.050342573
time:Stage                   0.057323548
time:Step                   -0.051674645
time:Age                     0.001710622
time:Income                  .          
time:Household               .          
time:Relationship            0.028936062
time:Caring.Hours            0.005906021
time:Hospital                0.013796071
Randomize:Relationship       0.689231867
Caregiver:Relationship      -0.219133837
Primary.Reason:Relationship  1.020935033
Employed:Relationship        0.963202917
Retired:Relationship         2.005238836
Education:Relationship       .          
Language:Relationship       -0.403092361
Gender:Relationship          0.209345226
Ethnicity:Relationship      -2.134370227
Race:Relationship            .          
Diagnosis:Relationship      -0.140269788
Stage:Relationship           .          
Step:Relationship            .          
Age:Relationship             .          
Income:Relationship          0.682436489
Household:Relationship       .          
Relationship:Caring.Hours    0.103816871
Relationship:Hospital       -0.528522983
```
