---
title: "data_for_lola"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      message = FALSE,
                      comment = "#>",
                      #results = "hide",
                      digits = 4,
                      error = FALSE)

## clean the R environment
graphics.off()
rm(list = ls())
freshr::freshr()

## load packages
library(here, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(gtsummary, quietly = TRUE)
library(flextable, quietly = TRUE)

## check the directory for the file
# here::dr_here()
here::set_here()

## the figure or results should be saved 
# paste0("foldername/Sfilename_workingresult_", 
#      Sys.Date(), ".filetype")
```


```{r}
load("~/Desktop/paper2023B/new_data/demo_clean_caregiver_factor_2_2023-12-13.Rdata")
load("~/Desktop/paper2023B/new_data/demo_clean_patient_factor_2_2023-12-13.Rdata")
```


```{r}
caregiver_demo <- caregiver_table_3 %>%
  select(caregiver_id = cid, patient_id = pid, 
         age, race_white, education)
patient_demo <- patient_table_3 %>% 
  select(caregiver_id = cid, patient_id = pid, 
         age, race_white, education)

```


```{r}
write_csv(caregiver_demo, 
          file = "new_data/pcori_caregiver_demo_age_race_education_lola.csv")
write_csv(patient_demo,
          file = "new_data/pcori_patient_demo_age_race_education_lola.csv")
```








