# Introduction

This is a book created from markdown and executable code for PCORI dataset

In this project, we created three new datasets with full caregiver data:

## `caregiver_table_1` 

This is the dataset with all the variables at original categories

1.  pid: Unique ID for patients

2.  cid: Unique ID for caregivers

3.  age \[int\]: What is your age in years?

4.  gender \[binary\]: What is your gender? **confirmed**

-   1 Male
-   2 Female
-   3 Other

5.  language/spanish \[binary\]: What language do you prefer to speak or read?

-   1 Spanish
-   2 English
-   3 Both

6.  ethnicity \[binary\]: You consider your ethnicity as:

-   1 Non-Hispanic
-   2 Hispanic

7.  race \[categorical\]: You consider your primary racial background as (Select all that apply):

-   1 race\_\_\_1 White
-   2 race\_\_\_2 Black
-   3 race\_\_\_3 Asian
-   4 race\_\_\_4 American Indian/Alaska Native
-   5 race\_\_\_5 Hawaiian/Pacific Islander
-   6 race\_\_\_6 Other

8.  primary_caregiver \[binary\]: Are you the PRIMARY caregiver of a patient diagnosed with lung, head and neck, and/or thyroid cancer?

-   1 Yes
-   0 No

9.  primary_reason \[binary\]: Have you cared for the patient for any reason or illness that is not related to their cancer treatment?

-   1 Yes
-   0 No

10. hours \[categorical\]: How many hours a week do you provide assistance, care, supervision, or companionship to the patient?

-   1 Less than 5 hours
-   2 5 to 10 hours
-   3 10 to 20 hours
-   4 More than 20 hours

11. household \[categorical\]: How many people in your household (including you) depend on your monthly income?

-   1 as 1
-   2 as 2
-   3 as 3
-   4 as 4
-   5 as 5
-   6 as 6
-   7 as 7
-   8 as 8 or more

12. relationship \[categorical\]: What is your role in the relationship with the patient? **a lot of people answer this question wrong...**

-   1 Husband/partner
-   2 Wife/partner
-   3 Mother
-   4 Father
-   5 Daughter
-   6 Son
-   7 Sister
-   8 Brother
-   9 Other relative
-   10 Non-relative

13. employed \[binary\]: Are you now employed?

-   1 Yes
-   0 No

14. retired \[binary\]: Are you retired?

-   1 Yes
-   0 No
-   -1 Unknown

15. education \[categorical\]: Choose the highest level of education you've completed

-   0 Missing or unknown
-   1 Grade school- 1
-   2 Grade school- 2
-   3 Grade school- 3
-   4 Grade school- 4
-   5 Grade school- 5
-   6 Grade school- 6
-   7 Grade school- 7
-   8 Grade school- 8
-   9 High school- 9
-   10 High school- 10
-   11 High school- 11
-   12 High school- 12
-   13 College- 1
-   14 College- 2
-   15 College- 3
-   16 College- 4
-   17 Post graduate- 5
-   18 Post graduate- 6
-   19 Post graduate- 7
-   20 Post-graduate- 8+

16. income \[categorical\]: Pick the category that best describes where your monthly income (after taxes) falls.

-   0 Minssing or unknown
-   1 Less than \$4,000
-   2 Less than \$5,400
-   3 Less than \$7,100
-   4 Less than \$8,100
-   5 Less than \$9,500
-   6 Less than \$10,900
-   7 Less than \$12,300
-   8 Less than \$13,700
-   9 More than \$13,701

17. randomize \[binary\]: randomization intervention condition

-   0 Control
-   1 Intervention

18. diagnosis \[categorical\]: What is the primary diagnosis of the patient you care for?

-   1 Lung cancer
-   2 Head and neck cancer
-   3 Other cancer
-   4 Thyroid cancer

19. stage \[categorical\]: At what stage was the patient's cancer diagnosed?

-   0 Stage 0
-   1 Stage I
-   2 Stage II
-   3 Stage III
-   4 Stage IV
-   5 Pending or Unknown

20. step \[categorical\]: Step at baseline

-   1 Step 1
-   2 Step 2
-   3 Step 3
-   4 Step 4
-   5 Unknown

21. hospital \[categorical\]: What hospital are you associated with?

-   1 Denver Health
-   2 St.Joe's
-   3 St.Mary's
-   4 National Jewish
-   5 UCCC

## `caregiver_table_2` and `caregiver_table_3`

Those are the datasets with merged or combined categories

1.  pid: Unique ID for patients

2.  cid: Unique ID for caregivers

3.  age \[int\]: What is your age in years?

4.  age_binary \[binary\]: Whether you are older than 60 years old?

-   1. Yes
-   2. No

5.  gender \[binary\]: What is your gender? **confirmed no missing**

-   1 Male
-   2 Female

6.  language/spanish \[binary\]: What language do you prefer to speak or read?

-   1 Spanish
-   2 English or both

7.  ethnicity \[binary\]: You consider your ethnicity as:

-   1 Non-Hispanic
-   2 Hispanic

8.  race \[categorical\]: You consider your primary racial background as (Select all that apply):

-   1 race White
-   2 race Other

9.  primary_caregiver \[binary\]: Are you the PRIMARY caregiver of a patient diagnosed with lung, head and neck, and/or thyroid cancer?

-   1 Yes
-   2 No

10.  primary_reason \[binary\]: Have you cared for the patient for any reason or illness that is not related to their cancer treatment?

-   1 Yes
-   2 No
-   0 Missing

11. hours \[categorical\]: How many hours a week do you provide assistance, care, supervision, or companionship to the patient?

-   0 Missing
-   1 Less than 10 hours
-   2 More than 10 hours

12. household \[categorical\]: How many people in your household (including you) depend on your monthly income?

-   0 as Missing
-   1 as Single person
-   2 as Two people 
-   3 as More than two people

13. relationship \[categorical\]: What is your role in the relationship with the patient? **a lot of people answer this question wrong...**

-   0 Missing
-   1 Couple or partner
-   2 Parents or children
-   3 Others relative or non-relative

14. employed \[binary\]: Are you now employed?

-   0 Missing
-   1 Yes
-   2 No

15. education \[categorical\]: Choose the highest level of education you've completed

-   0 Missing or unknown
-   1 High school level
-   2 College or graduate level

16. income \[categorical\]: Pick the category that best describes where your monthly income (after taxes) falls.

-   0 Minssing or unknown
-   1 Less than \$4,000
-   2 More than \$5,400

17. randomize \[binary\]: randomization intervention condition

-   0 Control
-   1 Intervention

18. diagnosis \[categorical\]: What is the primary diagnosis of the patient you care for?

-   0 Missing
-   1 Lung cancer
-   2 Head and neck cancer (including Thyroid cancer)

19. stage \[categorical\]: At what stage was the patient's cancer diagnosed?

-   1 Stage 0 I II
-   2 Stage III IV
-   0 Pending or Unknown

20. step \[categorical\]: Step at baseline

-   1 Step 1 & 2
-   2 Step 3 & 4
-   0 Pending or Unknown

21. hospital \[categorical\]: What hospital are you associated with?

-   1 Denver Health
-   2 St.Joe's
-   3 St.Mary's
-   4 National Jewish
-   5 UCCC



